stages:       
  - stagging
  - production

.deploy:
  before_script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
    - ssh -oStrictHostKeyChecking=no $USER@$HOST "cd $PROJECT_DIR && git pull origin $BRANCH"

deploy-to-dev:      
  stage: stagging
  extends: .deploy
  environment: develop
  only: 
    - develop

deploy-to-prod:      
  stage: production
  extends: .deploy
  environment: production
  only: 
    - main
  when: manual

